version: '3.9'

services:
  web:
    image: refinement-nginx:latest
    ports:
      - '8080:80'
    links:
      - php-fpm
  php-fpm:
    user: "${UID}:${GID}"
    image: refinement-php:latest
    volumes:
      - ./data:/opt/data
  longpolling:
    image: refinement-longpolling:latest
